--
-- PostgreSQL database dump
--

\restrict j55XbZ2yYn2gUVEP6plwalr69sLnFUTxsPEUhG42i5afyjHjCMyQQzY2e5RJlkj

-- Dumped from database version 16.15 (Debian 16.15-1.pgdg13+2)
-- Dumped by pg_dump version 16.15 (Debian 16.15-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: congestion_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.congestion_reports (
    id bigint NOT NULL,
    approval_count integer NOT NULL,
    congestion_level character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    custom_ttl_minutes integer,
    expires_at timestamp(6) without time zone NOT NULL,
    rejection_count integer NOT NULL,
    trust_score_processed boolean DEFAULT false NOT NULL,
    location_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT congestion_reports_congestion_level_check CHECK (((congestion_level)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying])::text[])))
);


--
-- Name: congestion_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.congestion_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.congestion_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.location_subscriptions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    location_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: location_subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.location_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.locations (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    default_ttl_minutes integer NOT NULL,
    geofence_radius integer NOT NULL,
    latitude numeric(10,7) NOT NULL,
    longitude numeric(10,7) NOT NULL,
    max_ttl_minutes integer NOT NULL,
    name character varying(100) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT locations_category_check CHECK (((category)::text = ANY ((ARRAY['SCHOOL'::character varying, 'CAFE'::character varying, 'RESTAURANT'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT locations_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


--
-- Name: locations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: peer_reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.peer_reviews (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    decision character varying(255) NOT NULL,
    report_id bigint NOT NULL,
    reviewer_id bigint NOT NULL,
    CONSTRAINT peer_reviews_decision_check CHECK (((decision)::text = ANY ((ARRAY['APPROVE'::character varying, 'REJECT'::character varying])::text[])))
);


--
-- Name: peer_reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.peer_reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.peer_reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_proposals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.place_proposals (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(200),
    latitude numeric(10,7) NOT NULL,
    longitude numeric(10,7) NOT NULL,
    name character varying(100) NOT NULL,
    rejection_reason character varying(200),
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    proposer_id bigint NOT NULL,
    CONSTRAINT place_proposals_category_check CHECK (((category)::text = ANY ((ARRAY['SCHOOL'::character varying, 'CAFE'::character varying, 'RESTAURANT'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT place_proposals_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: place_proposals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.place_proposals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_proposals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: point_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.point_transactions (
    id bigint NOT NULL,
    amount integer NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(200),
    sos_post_id bigint,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT point_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['SOS_ESCROW'::character varying, 'SOS_COMPLETE'::character varying, 'SOS_REFUND'::character varying, 'EARN_REPORT'::character varying, 'EARN_REVIEW'::character varying, 'EARN_PROPOSAL'::character varying, 'PURCHASE'::character varying])::text[])))
);


--
-- Name: point_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.point_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.point_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sos_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sos_posts (
    id bigint NOT NULL,
    content character varying(500) NOT NULL,
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone NOT NULL,
    location_id bigint NOT NULL,
    location_name character varying(100) NOT NULL,
    point_offer integer,
    status character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT sos_posts_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'ACCEPTED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: sos_posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sos_posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sos_posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sos_replies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sos_replies (
    id bigint NOT NULL,
    accepted boolean NOT NULL,
    completed boolean NOT NULL,
    content character varying(300) NOT NULL,
    created_at timestamp(6) without time zone,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: sos_replies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sos_replies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sos_replies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    nickname character varying(10) NOT NULL,
    password character varying(255) NOT NULL,
    point integer DEFAULT 0 NOT NULL,
    role character varying(255) NOT NULL,
    trust_score integer DEFAULT 0 NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: congestion_reports congestion_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.congestion_reports
    ADD CONSTRAINT congestion_reports_pkey PRIMARY KEY (id);


--
-- Name: location_subscriptions location_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.location_subscriptions
    ADD CONSTRAINT location_subscriptions_pkey PRIMARY KEY (id);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: peer_reviews peer_reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peer_reviews
    ADD CONSTRAINT peer_reviews_pkey PRIMARY KEY (id);


--
-- Name: place_proposals place_proposals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_proposals
    ADD CONSTRAINT place_proposals_pkey PRIMARY KEY (id);


--
-- Name: point_transactions point_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.point_transactions
    ADD CONSTRAINT point_transactions_pkey PRIMARY KEY (id);


--
-- Name: sos_posts sos_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sos_posts
    ADD CONSTRAINT sos_posts_pkey PRIMARY KEY (id);


--
-- Name: sos_replies sos_replies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sos_replies
    ADD CONSTRAINT sos_replies_pkey PRIMARY KEY (id);


--
-- Name: users uk2ty1xmrrgtn89xt7kyxx6ta7h; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk2ty1xmrrgtn89xt7kyxx6ta7h UNIQUE (nickname);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: location_subscriptions ukcna4y7tshkb2y9e2hcq5sjt7i; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.location_subscriptions
    ADD CONSTRAINT ukcna4y7tshkb2y9e2hcq5sjt7i UNIQUE (user_id, location_id);


--
-- Name: peer_reviews ukrrp7hjjl421kmi177muh6g975; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peer_reviews
    ADD CONSTRAINT ukrrp7hjjl421kmi177muh6g975 UNIQUE (report_id, reviewer_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: location_subscriptions fk1oc9n8ahskgn0u35wg7hwl8kw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.location_subscriptions
    ADD CONSTRAINT fk1oc9n8ahskgn0u35wg7hwl8kw FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: sos_replies fk315qjwxkrqciw3kb5v7pycptg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sos_replies
    ADD CONSTRAINT fk315qjwxkrqciw3kb5v7pycptg FOREIGN KEY (post_id) REFERENCES public.sos_posts(id);


--
-- Name: sos_replies fk3ggk8kwsvbcjs1k5xnemc69k4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sos_replies
    ADD CONSTRAINT fk3ggk8kwsvbcjs1k5xnemc69k4 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: sos_posts fk75cdcd2cawc4i1m10csyyyeim; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sos_posts
    ADD CONSTRAINT fk75cdcd2cawc4i1m10csyyyeim FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: point_transactions fkcqbvxpskb8p7mko50hokltu5b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.point_transactions
    ADD CONSTRAINT fkcqbvxpskb8p7mko50hokltu5b FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: congestion_reports fkecbgsq3rbpa2786ocso4gubvu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.congestion_reports
    ADD CONSTRAINT fkecbgsq3rbpa2786ocso4gubvu FOREIGN KEY (location_id) REFERENCES public.locations(id);


--
-- Name: peer_reviews fkefdi9hk12mrf7aw4mxmpg7wpj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peer_reviews
    ADD CONSTRAINT fkefdi9hk12mrf7aw4mxmpg7wpj FOREIGN KEY (report_id) REFERENCES public.congestion_reports(id);


--
-- Name: place_proposals fkfmrdvu688ygyveya8tgs0b8ky; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_proposals
    ADD CONSTRAINT fkfmrdvu688ygyveya8tgs0b8ky FOREIGN KEY (proposer_id) REFERENCES public.users(id);


--
-- Name: location_subscriptions fkg75rl5rulqqbxth3200cenhn1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.location_subscriptions
    ADD CONSTRAINT fkg75rl5rulqqbxth3200cenhn1 FOREIGN KEY (location_id) REFERENCES public.locations(id);


--
-- Name: peer_reviews fkppqu3n7tndcs680t1714cx2dd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peer_reviews
    ADD CONSTRAINT fkppqu3n7tndcs680t1714cx2dd FOREIGN KEY (reviewer_id) REFERENCES public.users(id);


--
-- Name: congestion_reports fkt2l24lx7a1k8gi4iwp0549v8u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.congestion_reports
    ADD CONSTRAINT fkt2l24lx7a1k8gi4iwp0549v8u FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict j55XbZ2yYn2gUVEP6plwalr69sLnFUTxsPEUhG42i5afyjHjCMyQQzY2e5RJlkj

